Repository phalcon/phalcon-devtools, pull requests merged in 2019-11, with the labels that each got.

#1350 #1305 - Fix URL during phalcon serve
  scripts/Phalcon/Web/Tools/Views/controllers/edit.volt
  scripts/Phalcon/Web/Tools/Views/controllers/generate.volt
  scripts/Phalcon/Web/Tools/Views/controllers/index.volt
  scripts/Phalcon/Web/Tools/Views/migrations/generate.volt
  scripts/Phalcon/Web/Tools/Views/migrations/index.volt
  scripts/Phalcon/Web/Tools/Views/migrations/run.volt
  scripts/Phalcon/Web/Tools/Views/models/edit.volt
  scripts/Phalcon/Web/Tools/Views/models/generate.volt
  scripts/Phalcon/Web/Tools/Views/models/index.volt
  scripts/Phalcon/Web/Tools/Views/scaffold/generate.volt
  templates/project/micro/config.ini
  templates/project/micro/config.php
  templates/project/micro/services.php
  templates/project/modules/config.ini
  templates/project/modules/config.php
  templates/project/modules/services_web.php
  templates/project/simple/config.ini
  templates/project/simple/config.php
  templates/project/simple/services.php
Labels: Bug - High

#1351 #1320 - Fix blank page on Scaffold form page
  scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php
Labels: Bug - Medium

#1352 #1320 - Fix blank page on Scaffold form page [v4]
  scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php
Labels: Bug - Medium

#1353 3.4.7
  scripts/Phalcon/Devtools/Version.php
  scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php
  scripts/Phalcon/Web/Tools/Views/controllers/edit.volt
  scripts/Phalcon/Web/Tools/Views/controllers/generate.volt
  scripts/Phalcon/Web/Tools/Views/controllers/index.volt
  scripts/Phalcon/Web/Tools/Views/migrations/generate.volt
  scripts/Phalcon/Web/Tools/Views/migrations/index.volt
  scripts/Phalcon/Web/Tools/Views/migrations/run.volt
  scripts/Phalcon/Web/Tools/Views/models/edit.volt
  scripts/Phalcon/Web/Tools/Views/models/generate.volt
  scripts/Phalcon/Web/Tools/Views/models/index.volt
  scripts/Phalcon/Web/Tools/Views/scaffold/generate.volt
  templates/project/micro/config.ini
  templates/project/micro/config.php
  templates/project/micro/services.php
  templates/project/modules/config.ini
  templates/project/modules/config.php
  templates/project/modules/services_web.php
  templates/project/simple/config.ini
  templates/project/simple/config.php
  templates/project/simple/services.php
Labels: Release

#1357 #1356 - Refactor service providers
  src/Bootstrap.php
  src/Exception/ProviderException.php
  src/Initializable.php
  src/Providers/AccessManagerProvider.php
  src/Providers/AnnotationsProvider.php
  src/Providers/AssetsProvider.php
  src/Providers/AssetsResourceProvider.php
  src/Providers/ConfigProvider.php
  src/Providers/DataCacheProvider.php
  src/Providers/DatabaseProvider.php
  src/Providers/DbUtilsProvider.php
  src/Providers/DispatcherProvider.php
  src/Providers/EventsManagerProvider.php
  src/Providers/FileSystemProvider.php
  src/Providers/FlashProvider.php
  src/Providers/FlashSessionProvider.php
  src/Providers/LoggerProvider.php
  src/Providers/MenuSiderbarProvider.php
  src/Providers/ModelsCacheProvider.php
  src/Providers/RegistryProvider.php
  src/Providers/RouterProvider.php
  src/Providers/SessionProvider.php
  src/Providers/SystemInfoProvider.php
  src/Providers/TagProvider.php
  src/Providers/UrlProvider.php
  src/Providers/ViewCacheProvider.php
  src/Providers/ViewProvider.php
  src/Providers/VoltProvider.php
  tests/unit/Providers/AccessManagerProviderTest.php
  tests/unit/Providers/AnnotationsProviderTest.php
  tests/unit/Providers/AssetsProviderTest.php
  tests/unit/Providers/AssetsResourceProviderTest.php
  tests/unit/Providers/ConfigProviderTest.php
  tests/unit/Providers/DataCacheProviderTest.php
  tests/unit/Providers/DatabaseProviderTest.php
  tests/unit/Providers/DbUtilsProviderTest.php
  tests/unit/Providers/DispatcherProviderTest.php
  tests/unit/Providers/EventsManagerProviderTest.php
  tests/unit/Providers/FileSystemProviderTest.php
  tests/unit/Providers/FlashProviderTest.php
  tests/unit/Providers/FlashSessionProviderTest.php
  tests/unit/Providers/LoggerProviderTest.php
  tests/unit/Providers/MenuSiderbarProviderTest.php
  tests/unit/Providers/ModelsCacheProviderTest.php
  tests/unit/Providers/RegistryProviderTest.php
  tests/unit/Providers/RouterProviderTest.php
  tests/unit/Providers/SessionProviderTest.php
  tests/unit/Providers/SystemInfoProviderTest.php
  tests/unit/Providers/TagProviderTest.php
  tests/unit/Providers/UrlProviderTest.php
  tests/unit/Providers/ViewCacheProviderTest.php
  tests/unit/Providers/ViewProviderTest.php
  tests/unit/Providers/VoltProviderTest.php
Labels: Testing

#1359 V4 Bug Fixes
  src/Bootstrap.php
  src/Providers/AccessManagerProvider.php
  src/Providers/ConfigProvider.php
  src/Providers/LoggerProvider.php
  src/Providers/RouterProvider.php
  src/Providers/VoltProvider.php
Labels: Bug - High

#1361 #1320 - Fix Scaffold white screen [v3.4]
  scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php
Labels: Bug - Medium, Scaffold

#1358 #1248 - Box 3 upgrade
  .ci/build-phar.sh
  .ci/install-box.sh
  .travis.yml
  bootstrap/autoload.php
  box.json
  composer.json
Labels: Installation

#1362 3.4.8
  scripts/Phalcon/Devtools/Version.php
  scripts/Phalcon/Web/Tools/Controllers/ScaffoldController.php
Labels: Release

#1366 #1365 - Integrate Codecov
  .codecov.yml
  .travis.yml
  README.md
  codeception.yml
Labels: Testing

#1367 #1365 - Codecov
  .travis.yml
Labels: Testing

#1373 #1368 - Add phalcon.phar comporession
  box.json
Labels: Installation, Release

#1371 #1363 - Unify GitHub token
  .travis.yml
Labels: Release

#1372 #1370 - Update Phalcon version to 4.0.0-RC.3
  .travis.yml
  bootstrap/autoload.php
  composer.json
  src/Version.php
Labels: Bug - Low, Installation

#1377 #1376 - CLI Commands review
  composer.json
  phalcon
  phalcon.bat
  src/Builder/Component/AbstractComponent.php
  src/Builder/Component/AllModels.php
  src/Builder/Component/Controller.php
  src/Builder/Component/Model.php
  src/Builder/Component/Module.php
  src/Builder/Component/Project.php
  src/Builder/Component/Scaffold.php
  src/Builder/Path.php
  src/Builder/Project/Cli.php
  src/Builder/Project/Modules.php
  src/Commands/Builtin/Controller.php
  src/Commands/Command.php
  src/Generator/Snippet.php
  src/Generator/Stub.php
  src/Providers/SessionProvider.php
  src/Script.php
  templates/module/Module.php
  templates/module/config.json
  templates/module/variables.json
  templates/project/cli/MainTask.php
  templates/project/cli/VersionTask.php
  templates/project/cli/bootstrap.php
  templates/project/cli/launcher
  templates/project/cli/services.php
  templates/project/micro/app.php
  templates/project/micro/config.php
  templates/project/micro/index.php
  templates/project/micro/services.php
  templates/project/modules/ControllerBase.php
  templates/project/modules/MainTask.php
  templates/project/modules/Module_cli.php
  templates/project/modules/Module_web.php
  templates/project/modules/VersionTask.php
  templates/project/modules/bootstrap_cli.php
  templates/project/modules/bootstrap_web.php
  templates/project/modules/index.php
  templates/project/modules/lancher.bat
  templates/project/modules/launcher
  templates/project/modules/routes.php
  templates/project/modules/services.php
  templates/project/modules/services_cli.php
  templates/project/modules/services_web.php
  templates/project/simple/ControllerBase.php
  templates/project/simple/config.php
  templates/project/simple/index.php
  templates/project/simple/router.php
  templates/project/simple/services.php
  templates/scaffold/no-forms/Controller.php
  tests/unit/Generator/SnippetTest.php
Labels: Testing

#1382 Fix deprecated errors (compiled*)
  templates/project/simple/services.php
Labels: Bug - Low

#1384 #1383 - CLI project args
  src/Commands/Command.php
  tests/console/GenerateProjectCept.php
Labels: Testing
