Repository phalcon/phalcon-devtools, pull requests merged in 2019-10, with the labels that each got.

#1322 #1321 - Remove ide stubs
  composer.json
  ide/gen-stubs.php
  ide/phpstorm/phalcon.bat
  ide/phpstorm/phalcon.sh
Labels: IDE

#1327 #1320 - Scaffold configs
  composer.json
  scripts/Phalcon/Builder/AllModels.php
  scripts/Phalcon/Builder/Component.php
  scripts/Phalcon/Builder/Controller.php
  scripts/Phalcon/Builder/Module.php
  scripts/Phalcon/Builder/Options.php
  scripts/Phalcon/Builder/Project.php
  scripts/Phalcon/Builder/Project/Cli.php
  scripts/Phalcon/Builder/Project/Micro.php
  scripts/Phalcon/Builder/Project/Modules.php
  scripts/Phalcon/Builder/Project/ProjectAware.php
  scripts/Phalcon/Builder/Project/ProjectBuilder.php
  scripts/Phalcon/Builder/Project/Simple.php
  scripts/Phalcon/Builder/Scaffold.php
Labels: Bug - Medium, Scaffold

#1337 Windows configuration
  phalcon.bat
Labels: Windows

#1340 Move Phalcon Migrations into separate repository
  composer.json
  scripts/Phalcon/Commands/Builtin/Migration.php
  scripts/Phalcon/Commands/Builtin/Model.php
  scripts/Phalcon/Console/OptionParserTrait.php
  scripts/Phalcon/Console/OptionStack.php
  scripts/Phalcon/Db/Adapter/Pdo/PdoMysql.php
  scripts/Phalcon/Db/Adapter/Pdo/PdoPostgresql.php
  scripts/Phalcon/Db/Dialect/DialectMysql.php
  scripts/Phalcon/Db/Dialect/DialectPostgresql.php
  scripts/Phalcon/Exception/Db/UnknownColumnTypeException.php
  scripts/Phalcon/Listeners/DbProfilerListener.php
  scripts/Phalcon/Migrations.php
  scripts/Phalcon/Mvc/Model/Migration.php
  scripts/Phalcon/Mvc/Model/Migration/Profiler.php
  scripts/Phalcon/Mvc/Model/Migration/TableAware/ListTablesDb.php
  scripts/Phalcon/Mvc/Model/Migration/TableAware/ListTablesInterface.php
  scripts/Phalcon/Mvc/Model/Migration/TableAware/ListTablesIterator.php
  scripts/Phalcon/Utils/Nullify.php
  scripts/Phalcon/Version/IncrementalItem.php
  scripts/Phalcon/Version/ItemCollection.php
  scripts/Phalcon/Version/ItemInterface.php
  scripts/Phalcon/Version/TimestampedItem.php
  scripts/Phalcon/Version/VersionAwareTrait.php
  scripts/Phalcon/Web/Tools/Controllers/MigrationsController.php
  tests/unit/Console/OptionStackTest.php
  tests/unit/Utils/NullifyTest.php
Labels: Migrations

#1344 3.4.5
  .travis.yml
  phalcon.bat
  scripts/Phalcon/Commands/Builtin/Project.php
  scripts/Phalcon/Devtools/Version.php
  tests/_data/console/app/projects/.gitignore
  tests/console/GenerateProjectCept.php
Labels: Release

#1345 #1336 - Project config.php file
  scripts/Phalcon/Builder/Project/Cli.php
  scripts/Phalcon/Builder/Project/Micro.php
  scripts/Phalcon/Builder/Project/Modules.php
  scripts/Phalcon/Builder/Project/Simple.php
  tests/console/GenerateProjectCept.php
Labels: Bug - Medium

#1346 #1336 - Project config.php file [v4]
  scripts/Phalcon/Builder/Project/Cli.php
  scripts/Phalcon/Builder/Project/Micro.php
  scripts/Phalcon/Builder/Project/Modules.php
  scripts/Phalcon/Builder/Project/Simple.php
  tests/console/GenerateProjectCept.php
Labels: Bug - Medium

#1347 3.4.6
  scripts/Phalcon/Builder/Project/Cli.php
  scripts/Phalcon/Builder/Project/Micro.php
  scripts/Phalcon/Builder/Project/Modules.php
  scripts/Phalcon/Builder/Project/Simple.php
  scripts/Phalcon/Devtools/Version.php
  tests/console/GenerateProjectCept.php
Labels: Release
