Repository phalcon/phalcon-devtools, pull requests merged in 2019-12, with the labels that each got.

#1388 Add Dockerfile for generate phar file
  Makefile
  README.md
  build/BuildPharDockerfile
Labels: Installation

#1389 3.4.9
  Makefile
  README.md
  build/BuildPharDockerfile
  scripts/Phalcon/Devtools/Version.php
Labels: Installation

#1390 Add column types without size
  scripts/Phalcon/Mvc/Model/Migration.php
Labels: Bug - Low, Migrations

#1391 3.4.10
  scripts/Phalcon/Devtools/Version.php
  scripts/Phalcon/Mvc/Model/Migration.php
Labels: Migrations, Release

#1393 #1392 - Rename lancher.bat to launcher.bat
  composer.json
  templates/project/modules/launcher.bat
  tests/acceptance/Web/Tools/Controllers/MigrationsControllerCest.php
Labels: Bug - Low

#1397 #1395 - Change Deprecated volt options
  templates/project/modules/services.php
Labels: Bug - Low

#1398 #1394 - Webtools flash messages review
  src/Bootstrap.php
  src/Providers/FlashSessionProvider.php
  src/Providers/SessionProvider.php
  src/Web/Tools/Controllers/ControllersController.php
  src/Web/Tools/Controllers/MigrationsController.php
  src/Web/Tools/Controllers/ModelsController.php
  src/Web/Tools/Controllers/ScaffoldController.php
  src/Web/Tools/Controllers/SystemInfoController.php
  src/Web/Tools/Views/controllers/edit.volt
  src/Web/Tools/Views/controllers/generate.volt
  src/Web/Tools/Views/controllers/index.volt
  src/Web/Tools/Views/controllers/view.volt
  src/Web/Tools/Views/migrations/generate.volt
  src/Web/Tools/Views/migrations/index.volt
  src/Web/Tools/Views/migrations/run.volt
  src/Web/Tools/Views/models/edit.volt
  src/Web/Tools/Views/models/generate.volt
  src/Web/Tools/Views/models/index.volt
  src/Web/Tools/Views/models/view.volt
  src/Web/Tools/Views/scaffold/generate.volt
  src/Web/Tools/Views/system_info/index.volt
  templates/project/modules/services_web.php
  templates/project/simple/services.php
  tests/acceptance/Web/Tools/Controllers/ControllersControllerCest.php
  tests/acceptance/Web/Tools/Controllers/MigrationsControllerCest.php
  tests/acceptance/Web/Tools/Controllers/ModelsControllerCest.php
  tests/unit/Providers/FileSystemProviderTest.php
  tests/unit/Providers/FlashSessionProviderTest.php
Labels: Bug - Low, WebTools

#1404 #1402 - Remove requirements of SessionBag
  templates/scaffold/no-forms/Controller.php
  templates/scaffold/no-forms/views/edit.phtml
  templates/scaffold/no-forms/views/edit.volt
  templates/scaffold/no-forms/views/index.phtml
  templates/scaffold/no-forms/views/index.volt
  templates/scaffold/no-forms/views/new.phtml
  templates/scaffold/no-forms/views/new.volt
  templates/scaffold/no-forms/views/search.phtml
Labels: Bug - Low

#1405 #1400 - Fix empty namespace for controllers and models
  src/Builder/Component/Scaffold.php
  tests/console/GenerateScaffoldCept.php
Labels: Bug - Low

#1406 #1399 - Exclude size for TYPE_DOUBLE
  scripts/Phalcon/Mvc/Model/Migration.php
Labels: Bug - Medium

#1407 3.4.11
  scripts/Phalcon/Devtools/Version.php
  scripts/Phalcon/Mvc/Model/Migration.php
Labels: Migrations, Release
