Repository phalcon/phalcon-devtools, pull requests merged in 2020-04, with the labels that each got.

#1446 GitHub actions / Test CI / Add PostgreSQL tests
  .ci/github_set_env.sh
  .ci/link_devtools.sh
  .ci/serve-webtools.sh
  .github/workflows/tests.yml
  .travis.yml
  src/Providers/ConfigProvider.php
  src/Providers/DatabaseProvider.php
  tests/.env.test
  tests/_ci/environment
  tests/_ci/setup_dbs_github.sh
  tests/_data/acceptance/.gitignore
  tests/_data/acceptance/mysql/config.php
  tests/_data/acceptance/pgsql/config.php
  tests/_data/console/app/mysql/config.php
  tests/_data/fixtures/Traits/DiTrait.php
  tests/_data/schemas/postgresql/dump.sql
  tests/_envs/mysql.yml
  tests/_envs/pgsql.yml
  tests/_support/Helper/Acceptance.php
  tests/acceptance/Web/Template/ScaffoldVoltCest.php
  tests/acceptance/Web/Tools/Controllers/ControllersControllerCest.php
  tests/acceptance/Web/Tools/Controllers/ErrorControllerCest.php
  tests/acceptance/Web/Tools/Controllers/IndexControllerCest.php
  tests/acceptance/Web/Tools/Controllers/MigrationsControllerCest.php
  tests/acceptance/Web/Tools/Controllers/ModelsControllerCest.php
  tests/acceptance/Web/Tools/Controllers/ScaffoldControllerCest.php
  tests/acceptance/Web/Tools/Controllers/SystemInfoControllerCest.php
Labels: Testing

#1449 Fix error Psalm - Calling empty on a boolean value is almost certainly unintended
  src/Builder/Component/Model.php
  src/Builder/Path.php
  src/Generator/Snippet.php
Labels: Bug - Low

#1450 fix: #1410 - webtools not enabled by default
  CHANGELOG.md
  src/Builder/Project/Simple.php
  tests/console/GenerateProjectCept.php
Labels: Bug - Low

#1454 Test scaffold generated files
  src/Builder/Project/Simple.php
  src/Web/Tools/Controllers/ScaffoldController.php
  templates/scaffold/no-forms/views/search.phtml
  templates/scaffold/no-forms/views/search.volt
  tests/_data/schemas/mysql/dump.sql
  tests/_data/schemas/postgresql/dump.sql
  tests/acceptance.suite.yml
  tests/acceptance/Web/Template/ScaffoldVoltCest.php
  tests/acceptance/Web/Template/phtml/ScaffoldPhtmlCest.php
  tests/acceptance/Web/Template/volt/ScaffoldVoltCest.php
Labels: Testing

#1456 Fix .phar build
  CHANGELOG.md
  box.json
Labels: Bug - Medium

#1457 4.0.3
  CHANGELOG.md
  bootstrap/autoload.php
  box.json
  src/Builder/Project/Simple.php
  src/Providers/DatabaseProvider.php
  src/Version.php
  src/Web/Tools/Controllers/ScaffoldController.php
  templates/scaffold/no-forms/views/search.phtml
  templates/scaffold/no-forms/views/search.volt
  tests/_data/schemas/mysql/dump.sql
  tests/_data/schemas/postgresql/dump.sql
  tests/acceptance.suite.yml
  tests/acceptance/Web/Template/ScaffoldVoltCest.php
  tests/acceptance/Web/Template/phtml/ScaffoldPhtmlCest.php
  tests/acceptance/Web/Template/volt/ScaffoldVoltCest.php
Labels: Release
